//
//  TweakCharacterizationTests.swift
//  VexSignTests
//
//  Phase 1 Step 8 — tweak analysis/detection characterization.
//
//  Pins TweakAnalyzer's classification and recommendations against the
//  committed fixture corpus (synthetic Mach-Os generated by
//  tools/make_test_fixtures.py), plus TweakFileType mapping, TweakExtractor
//  discovery and MachOReader's defensive parsing. The future
//  TweakInjectionPlan architecture is deliberately NOT introduced here.
//

import XCTest
import Foundation
@testable import VexSign

final class TweakCharacterizationTests: XCTestCase {

	private var tempDirs: [URL] = []

	override func tearDown() {
		for url in tempDirs {
			try? FileManager.default.removeItem(at: url)
		}
		tempDirs.removeAll()
		super.tearDown()
	}

	private func fixture(_ name: String) -> URL {
		TestFixtures.url("Tweaks/\(name)")
	}

	// MARK: - File type mapping

	func testTweakFileTypeMapsKnownExtensions() {
		XCTAssertEqual(TweakFileType(fileExtension: "dylib"), .dylib)
		XCTAssertEqual(TweakFileType(fileExtension: "DYLIB"), .dylib)
		XCTAssertEqual(TweakFileType(fileExtension: "deb"), .deb)
		XCTAssertEqual(TweakFileType(fileExtension: "framework"), .framework)
		XCTAssertEqual(TweakFileType(fileExtension: "bundle"), .bundle)
		XCTAssertEqual(TweakFileType(fileExtension: "appex"), .appex)
		XCTAssertEqual(TweakFileType(fileExtension: "txt"), .other)
		XCTAssertEqual(TweakFileType(fileExtension: ""), .other)
	}

	// MARK: - dylib analysis

	func testPlainDylibLinksOnlySystemLibraries() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("plain.dylib"), type: .dylib)
		XCTAssertEqual(analysis.fileType, .dylib)
		XCTAssertEqual(analysis.linkedLibraries, ["/usr/lib/libSystem.B.dylib"])
		XCTAssertFalse(analysis.needsSubstrate)
		XCTAssertFalse(analysis.usesRpath)
		XCTAssertTrue(analysis.warnings.isEmpty)
		// Plain dylibs inject at the executable, file lands at the app root.
		XCTAssertEqual(analysis.recommendedPath, .executable_path)
		XCTAssertEqual(analysis.recommendedFolder, .root)
		XCTAssertTrue(analysis.hasRecommendation)
	}

	func testSubstrateDylibIsDetectedFromLoadCommands() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("substrate.dylib"), type: .dylib)
		XCTAssertTrue(analysis.needsSubstrate, "CydiaSubstrate load commands must trigger substrate detection")
		XCTAssertTrue(analysis.linkedLibraries.contains("/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate"))
		// Without an app context the note explains ElleKit will be added.
		XCTAssertTrue(analysis.notes.contains { $0.contains("ElleKit") }, "notes: \(analysis.notes)")
	}

	func testSubstrateNoteChangesWhenAppAlreadyShipsIt() async throws {
		// Build a fake app that already carries CydiaSubstrate.
		let app = FileManager.default.temporaryDirectory
			.appendingPathComponent("VexSignSubstrateApp_\(UUID().uuidString)", isDirectory: true)
		tempDirs.append(app)
		try FileManager.default.createDirectory(
			at: app.appendingPathComponent("Frameworks/CydiaSubstrate.framework", isDirectory: true),
			withIntermediateDirectories: true
		)

		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("substrate.dylib"), type: .dylib, appURL: app)
		XCTAssertTrue(analysis.needsSubstrate)
		XCTAssertTrue(analysis.notes.contains { $0.contains("already includes it") }, "notes: \(analysis.notes)")
	}

	func testRpathDylibRecommendsFrameworksFolderAndSurfacesFrameworkDeps() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("rpath.dylib"), type: .dylib)
		XCTAssertTrue(analysis.usesRpath)
		XCTAssertEqual(analysis.recommendedPath, .rpath)
		XCTAssertEqual(analysis.recommendedFolder, .frameworks)

		// @rpath/Orion.framework/Orion surfaces as a non-critical dependency.
		XCTAssertTrue(analysis.dependencies.contains { $0.name == "Orion" && $0.critical == false })
	}

	func testGarbageDylibWarnsInsteadOfCrashing() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("garbage.dylib"), type: .dylib)
		XCTAssertTrue(analysis.linkedLibraries.isEmpty)
		XCTAssertFalse(analysis.needsSubstrate)
		XCTAssertTrue(analysis.warnings.contains { $0.contains("load commands") }, "warnings: \(analysis.warnings)")
	}

	// MARK: - framework / bundle / appex analysis

	func testFrameworkAnalysisForcesRpathFrameworksPlacement() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("Sample.framework"), type: .framework)
		XCTAssertEqual(analysis.fileType, .framework)
		XCTAssertEqual(analysis.recommendedPath, .rpath)
		XCTAssertEqual(analysis.recommendedFolder, .frameworks)
		XCTAssertFalse(analysis.linkedLibraries.isEmpty)
	}

	func testFrameworkWithoutExecutableWarnsButStillRecommends() async throws {
		// An empty .framework directory has no readable executable.
		let empty = FileManager.default.temporaryDirectory
			.appendingPathComponent("Empty_\(UUID().uuidString).framework", isDirectory: true)
		tempDirs.append(empty)
		try FileManager.default.createDirectory(at: empty, withIntermediateDirectories: true)

		let analysis = await TweakAnalyzer.analyze(fileURL: empty, type: .framework)
		XCTAssertTrue(analysis.warnings.contains { $0.contains("no readable executable") })
		XCTAssertEqual(analysis.recommendedFolder, .frameworks)
	}

	func testResourceBundleIsNotInjectable() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("Resource.bundle"), type: .bundle)
		XCTAssertEqual(analysis.fileType, .bundle)
		XCTAssertNil(analysis.recommendedPath)
		XCTAssertNil(analysis.recommendedFolder)
		XCTAssertFalse(analysis.hasRecommendation)
	}

	func testAppexAnalysisReadsTheExtensionPoint() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("Share.appex"), type: .appex)
		XCTAssertEqual(analysis.fileType, .appex)
		XCTAssertTrue(analysis.summary.contains("Share"), "summary: \(analysis.summary)")
		XCTAssertTrue(analysis.notes.contains { $0.contains("com.apple.share-services") })
		XCTAssertNil(analysis.recommendedPath, "appexes are placed, not injected")
	}

	// MARK: - deb analysis

	func testSubstrateDebIsDetectedViaDependsAndInstallPaths() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("substrate-tweak.deb"), type: .deb)
		XCTAssertEqual(analysis.fileType, .deb)
		XCTAssertTrue(analysis.needsSubstrate)
		XCTAssertTrue(analysis.debInstallPaths.contains { $0.contains("MobileSubstrate/DynamicLibraries/tweak.dylib") })
		XCTAssertTrue(analysis.dependencies.contains { $0.name == "CydiaSubstrate" && $0.critical == true })
		XCTAssertTrue(analysis.summary.contains("Test tweak"), "summary: \(analysis.summary)")
	}

	func testPlainDebHasNoSubstrateRequirement() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("plain-tweak.deb"), type: .deb)
		XCTAssertFalse(analysis.needsSubstrate)
		XCTAssertTrue(analysis.dependencies.contains { $0.name == "preferenceloader" })
		XCTAssertFalse(analysis.dependencies.contains { $0.name == "CydiaSubstrate" })
	}

	func testEmptyDebWarnsAboutMissingInjectables() async {
		let analysis = await TweakAnalyzer.analyze(fileURL: fixture("empty.deb"), type: .deb)
		XCTAssertTrue(analysis.debInstallPaths.isEmpty)
		XCTAssertTrue(analysis.warnings.contains { $0.contains("No dylibs/frameworks/bundles") })
	}

	func testUnknownTypeIsReportedWithoutCrashing() async throws {
		let unknown = FileManager.default.temporaryDirectory.appendingPathComponent("unknown.bin")
		tempDirs.append(unknown)
		try Data("anything".utf8).write(to: unknown)

		let analysis = await TweakAnalyzer.analyze(fileURL: unknown, type: .other)
		XCTAssertEqual(analysis.fileType, .other)
		XCTAssertFalse(analysis.hasRecommendation)
	}

	// MARK: - MachOReader defensiveness

	func testMachOReaderRejectsGarbageAndShortInputs() throws {
		for data in [Data(), Data("tiny".utf8), Data(repeating: 0xFF, count: 512)] {
			let url = FileManager.default.temporaryDirectory.appendingPathComponent("macho-\(UUID().uuidString)")
			tempDirs.append(url)
			try data.write(to: url)
			XCTAssertTrue(MachOReader.dylibs(forExecutableAt: url).isEmpty)
		}
	}

	func testMachOReaderReadsCommittedFixtureLoadCommands() {
		XCTAssertEqual(
			MachOReader.dylibs(forExecutableAt: fixture("substrate.dylib")),
			[
				"/usr/lib/libSystem.B.dylib",
				"/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate",
				"/usr/lib/libsubstrate.dylib",
			]
		)
	}

	// MARK: - TweakExtractor discovery

	func testExtractorFindsEveryInjectableInATree() {
		let candidates = TweakExtractor.candidates(inDirectory: TestFixtures.url("Tweaks"))
		let names = Set(candidates.map { $0.name })

		for expected in ["plain.dylib", "substrate.dylib", "rpath.dylib", "garbage.dylib",
		                 "Sample.framework", "Resource.bundle", "Share.appex",
		                 "substrate-tweak.deb", "plain-tweak.deb", "empty.deb"] {
			XCTAssertTrue(names.contains(expected), "missing candidate \(expected); got \(names.sorted())")
		}

		// Types map onto the file extensions.
		for candidate in candidates {
			XCTAssertEqual(candidate.type, TweakFileType(fileExtension: candidate.url.pathExtension))
			XCTAssertGreaterThan(candidate.size, 0)
		}
	}

	func testExtractorScansAFixtureIPA() async throws {
		let ipa = TestFixtures.url("IPAs/Nested.ipa")
		let (workDir, candidates) = try await TweakExtractor.extract(fromIPA: ipa)
		tempDirs.append(workDir)

		let names = Set(candidates.map { $0.name })
		XCTAssertTrue(names.contains("Extra.dylib"), "got \(names.sorted())")
		XCTAssertTrue(names.contains("Alpha.framework"), "got \(names.sorted())")
		XCTAssertTrue(names.contains("Widget.appex"), "got \(names.sorted())")
	}

	func testExtractorRejectsAnArchiveWithoutAnApp() async throws {
		let noApp = try UnsafeArchiveFactory.write(
			MiniZipWriter.zip([MiniZipWriter.Entry(name: "readme.txt", content: Data("hi".utf8))]),
			ext: "ipa"
		)
		tempDirs.append(noApp)

		do {
			_ = try await TweakExtractor.extract(fromIPA: noApp)
			XCTFail("an archive without a .app must fail")
		} catch let error as TweakExtractorError {
			if case .payloadNotFound = error { /* expected */ } else {
				XCTFail("unexpected TweakExtractorError: \(error)")
			}
		}
	}
}
